export const LOCAL_STORAGE_DB_NAME = import.meta.env.VITE_LOCAL_STORAGE_DB_NAME;

export const LOCAL_STORAGE_USER_KEY = import.meta.env.VITE_LOCAL_STORAGE_USER_KEY;
export const LOCAL_STORAGE_LAST_REMEMBERED_USERNAME_KEY = import.meta.env.VITE_LOCAL_STORAGE_LAST_REMEMBERED_USERNAME_KEY;
export const LOCAL_STORAGE_ACCOUNTS_KEY = import.meta.env.VITE_LOCAL_STORAGE_ACCOUNTS_KEY;
export const LOCAL_STORAGE_RECENT_ACCOUNTS_KEY = import.meta.env.VITE_LOCAL_STORAGE_RECENT_ACCOUNTS_KEY;